# Generated by Django 2.1.5 on 2019-01-22 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190122_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='approve_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 22, 12, 35, 38, 460445, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 22, 12, 35, 38, 459591, tzinfo=utc)),
        ),
    ]
