# Generated by Django 2.1.7 on 2019-02-17 20:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190122_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 17, 20, 43, 25, 470875, tzinfo=utc)),
        ),
    ]
